### ISSUE TITLE
Hot reloading CSS

### ISSUE THREAD

**Issue by pablopaul** [timaschew/r3-foundation-boilerplate#2]
Should the boilerplate also hot reload / refresh the generated CSS or is this not in the scope of this project?

**Comment by timaschew** [comment]
You're right, HMR should be scope of the project. 
Currently the focus is on the development setup, so it's definitively scope.

BTW: I found out some days ago, that TextExtract Plugin is not working with HRM or at least with a combination of sourcemaps and/or Sass.

**Comment by timaschew** [comment]
So I got HRM working with this setup

``` javascript
      {
        // for some modules like foundation
        test: /\.scss$/,
        exclude: [/node_modules/], // sassLoader will include node_modules explicitly
        loader: CSS_HRM ?
          'style!css?sourceMap!postcss!sass?sourceMap&sourceComments' :
          ExtractTextPlugin.extract("style", "css?sourceMap!postcss!sass?sourceMap&sourceComments")
      },
      {
        test: /\.css$/,
        loader: CSS_HRM ? 'style!css?sourceMap!postcss' : ExtractTextPlugin.extract("style", "css?sourceMap!postcss")
      }
```

But unfortunately, it doesn't load font awesome and some other stuff properly anymore.

maybe related issues:
https://github.com/webpack/extract-text-webpack-plugin/issues/30
https://github.com/jtangelder/sass-loader/issues/194
