### ISSUE TITLE
Using reveal modal

### ISSUE THREAD

**Issue by abigwonderful** [timaschew/r3-foundation-boilerplate#3]
First off - thanks for the boilerplate @timaschew !

I'm very new to react and redux and taking things apart and then putting them back together again to try to wrap my head around how this is all set up. So far so good.

One question I have relates to using some of the build in foundation js. How would one go about calling a reveal modal on a component using your setup? If you can provide a little guidance, I'd be happy to contribute to the documentation (granted I can figure it out!)
Cheers!

**Comment by timaschew** [comment]
Hi Sam,

I needet this feature as well some time ago (before I had this boilerplate) and found a solution but it had some issues and was little bit complex, so I would'nt prefer to show it at first.
Just searched for **react foundation reveal modal** and I get these solutions
- http://blackmuttmedia.com/blog/a-kinder-gentler-reactjs-foundation-reveal-modal/
- https://gist.github.com/tarjei/326a1db2616d0d473ec1
