### ISSUE TITLE
Unable to start node server.

### ISSUE THREAD

**Issue by nitte1993** [timaschew/r3-foundation-boilerplate#4]
`npm start` throws this error.

npm ERR! Failed at the r3-foundation@1.0.0 start script 'node server'.
npm ERR! This is most likely a problem with the r3-foundation package,
npm ERR! not with npm itself.

Here's the npm-debug.log file
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart r3-foundation@1.0.0
6 info start r3-foundation@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info r3-foundation@1.0.0 Failed to exec start script
9 verbose stack Error: r3-foundation@1.0.0 start: `node server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid r3-foundation@1.0.0
11 verbose cwd /Users/nitesh/Documents/campusDiaries/foundation-react/r3-foundation-boilerplate
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error r3-foundation@1.0.0 start: `node server`
17 error Exit status 1
18 error Failed at the r3-foundation@1.0.0 start script 'node server'.
18 error This is most likely a problem with the r3-foundation package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs r3-foundation
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls r3-foundation
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by nitte1993** [comment]
Hi ,
To remove the error regarding serve-static. 
DO `npm install serve-static`

Make sure you have also updated it in the package.json.
or else do `npm install serve-static --save-dev`

**Comment by timaschew** [comment]
Thanks, I fixed it in 0c21f920325fd1ecf3f84b1e56e5634dbe2d9c91
