### ISSUE TITLE
How do I run this in production mode?

### ISSUE THREAD

**Issue by nitte1993** [timaschew/r3-foundation-boilerplate#5]
I tried setting the 
npm start to   

`"start": "NODE_ENV=production node server.js",
`

But it still starts in development mode!. How do I make it run in production mode?

**Comment by rajchourasia** [comment]
facing the same issue. are there any specific settings to done?

**Comment by timaschew** [comment]
When using webpack it needs some special handling, fixed in 4f672207f1fc2940a2e65e0f3a07e326d9c1f657

So you can now just run `NODE_ENV=production npm start`
